name: Test
on:
  push:
    branches: [ main ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends nodejs npm
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get install -y --no-install-recommends ninja-build meson pkg-config libzstd-dev
      - name: Build
        run: |
          meson setup build -Ddefault_library=static -Dc_args=-static -Dc_link_args=-static --buildtype=release
          meson compile -C build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dpatchz
          path: build/dpatchz

  # Tests by running dpatchz on some random 2.4.3 -> 2.5.1 partial diffs
  # We don't patch the whole program because that would take too much storage and time
  test:
    runs-on: ubuntu-latest
    needs: build-and-upload
    strategy:
      matrix:
        diff_number: [ 0, 1, 2, 3, 5, 7]
        include:
          - api: https://hw-pcdownload-qcloud.aki-game.net/launcher/game/G153/50004/2.5.1/IYOwHBLfeAXMxVgHwGybWvvSqiDnPlbs/resource/50004/2.5.1/2.4.3/indexFile.json
          - base_url: https://hw-pcdownload-aws.aki-game.net/launcher/game/G153/50004/2.4.3/SZqhxsTkRdyUlZaLhFuJobLKYodsAwan/zip
          - patch_url: https://hw-pcdownload-aws.aki-game.net/launcher/game/G153/50004/2.5.0/jLYdEEVBgAgPqJgUZlVztdMPFnUJnRjQ/resource/50004/2.5.0/2.4.3/resources
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: dpatchz
          path: .
      - name: Download files
        run: |
          export API='${{ matrix.api }}'
          export BASE_URL='${{ matrix.base_url }}'
          export PATCH_URL='${{ matrix.patch_url }}'

          mkdir testfiles
          curl -L "$API" | jq -r '.groupInfos[${{ matrix.diff_number }}].srcFiles[].dest' \
            | while read -r RELPATH; do
                mkdir -p "testfiles/$(dirname "$RELPATH")"
                curl -L "$BASE_URL/$RELPATH" -o "testfiles/$RELPATH"
              done

          curl -L "$API" | jq -r '.groupInfos[${{ matrix.diff_number }}].dest' | xargs -I{} -- curl -sL "$PATCH_URL/{}" -o patch.krpdiff
          curl -L "$API" | jq -r '.groupInfos[${{ matrix.diff_number }}].dstFiles[] | "\(.md5)  \(.dest)"' > checksums.txt
      - name: Patch
        run: | 
          chmod +x ./dpatchz
          ./dpatchz -v -i patch.krpdiff testfiles
      - name: Verify checksum
        run: |
          cd testfiles
          md5sum -c ../checksums.txt
