name: Build
on:
  push:
    branches: [ main ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends nodejs npm
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get install -y --no-install-recommends ninja-build meson pkg-config libzstd-dev
      - name: Build
        run: |
          meson setup build -Ddefault_library=static -Dc_args=-static -Dc_link_args=-static --buildtype=release
          meson compile -C build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dpatchz-${{ github.sha }}
          path: build/dpatchz
