name: Release
on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Install Node
        run: apk -U --no-cache add nodejs npm
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: apk -U --no-cache add build-base cmake pkgconfig zstd-static zstd-dev curl jq
      - name: Build
        run: |
          cmake -B build -S . \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_EXE_LINKER_FLAGS="-static" \
            -DCMAKE_FIND_LIBRARY_SUFFIXES=".a"
          cmake --build build
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: dpatchz ${{ github.ref_name }}
          artifacts: build/dpatchz
